# Organización y clave del proyecto
sonar.organization=codeurjc-students
sonar.projectKey=codeurjc-students_2025-Frict

# Directorios de código fuente y tests, relativos a la raíz
sonar.sources=backend/src/main/java,frontend/src
sonar.tests=backend/src/test/java,frontend/src

# Binarios del backend compilados (Necesario para el análisis en Java fuera de Maven)
sonar.java.binaries=backend/target/classes

# Inclusiones y exclusiones (adaptadas a las nuevas rutas relativas)
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=backend/**/model/**,backend/**/dto/**,backend/**/repository/**,backend/**/config/**,backend/**/utils/**,backend/**/BackendApplication.java,frontend/src/**/*.spec.ts,frontend/src/environments/**,frontend/src/app/models/**,frontend/src/app/services/**,frontend/src/app/*.*,frontend/src/app/utils/**

# Informes de cobertura de JaCoCo (Backend) y LCOV (Frontend)
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/frontend/lcov.info
