-- V1__baseline.sql
-- Flyway baseline migration for 2025-Frict.
--
-- On the FIRST production deployment, the schema is created by Hibernate (ddl-auto=update)
-- and Flyway marks this migration as the baseline (spring.flyway.baseline-on-migrate=true).
--
-- Subsequent schema changes should be added as V2__description.sql, V3__description.sql, etc.
-- After the first deployment, switch ddl-auto from 'update' to 'validate'.
--
-- This file is intentionally empty: the baseline is the Hibernate-generated schema.
SELECT 1;
