import {Injectable} from '@angular/core';
import {Title} from '@angular/platform-browser';
import {AuthService} from '../services/auth.service';

export type IconType = 'client' | 'admin';

@Injectable({
  providedIn: 'root'
})
export class UiService {
  constructor(private titleService: Title,
              private authService: AuthService) {
  }


  public readonly CLIENT_APP_NAME = 'MiTienda';
  public readonly ADMIN_APP_NAME = 'Frict';
  public readonly APP_USER_LOGO = '/shopLogo.png';
  public readonly APP_ADMIN_LOGO = '/frictLogo.png';
  private readonly PREDEFINED_ICONS: Record<string, string> = {
    client: '/shopLogo.png',
    admin: '/frictLogo.png',
  };

  public readonly AVAILABLE_ICONS = [
    { label: 'Libreta de direcciones', value: 'pi pi-address-book' },
    { label: 'Alinear al centro', value: 'pi pi-align-center' },
    { label: 'Justificar', value: 'pi pi-align-justify' },
    { label: 'Alinear a la izquierda', value: 'pi pi-align-left' },
    { label: 'Alinear a la derecha', value: 'pi pi-align-right' },
    { label: 'Amazon', value: 'pi pi-amazon' },
    { label: 'Android', value: 'pi pi-android' },
    { label: 'Doble ángulo abajo', value: 'pi pi-angle-double-down' },
    { label: 'Doble ángulo izquierda', value: 'pi pi-angle-double-left' },
    { label: 'Doble ángulo derecha', value: 'pi pi-angle-double-right' },
    { label: 'Doble ángulo arriba', value: 'pi pi-angle-double-up' },
    { label: 'Ángulo abajo', value: 'pi pi-angle-down' },
    { label: 'Ángulo izquierda', value: 'pi pi-angle-left' },
    { label: 'Ángulo derecha', value: 'pi pi-angle-right' },
    { label: 'Ángulo arriba', value: 'pi pi-angle-up' },
    { label: 'Apple', value: 'pi pi-apple' },
    { label: 'Flecha circular abajo', value: 'pi pi-arrow-circle-down' },
    { label: 'Flecha circular izquierda', value: 'pi pi-arrow-circle-left' },
    { label: 'Flecha circular derecha', value: 'pi pi-arrow-circle-right' },
    { label: 'Flecha circular arriba', value: 'pi pi-arrow-circle-up' },
    { label: 'Flecha abajo', value: 'pi pi-arrow-down' },
    { label: 'Flecha abajo izquierda', value: 'pi pi-arrow-down-left' },
    { label: 'Contraer al centro', value: 'pi pi-arrow-down-left-and-arrow-up-right-to-center' },
    { label: 'Flecha abajo derecha', value: 'pi pi-arrow-down-right' },
    { label: 'Flecha izquierda', value: 'pi pi-arrow-left' },
    { label: 'Flecha derecha', value: 'pi pi-arrow-right' },
    { label: 'Doble flecha horizontal', value: 'pi pi-arrow-right-arrow-left' },
    { label: 'Flecha arriba', value: 'pi pi-arrow-up' },
    { label: 'Flecha arriba izquierda', value: 'pi pi-arrow-up-left' },
    { label: 'Flecha arriba derecha', value: 'pi pi-arrow-up-right' },
    { label: 'Expandir desde el centro', value: 'pi pi-arrow-up-right-and-arrow-down-left-from-center' },
    { label: 'Flechas expansión', value: 'pi pi-arrows-alt' },
    { label: 'Flechas horizontales', value: 'pi pi-arrows-h' },
    { label: 'Flechas verticales', value: 'pi pi-arrows-v' },
    { label: 'Asterisco', value: 'pi pi-asterisk' },
    { label: 'Arroba', value: 'pi pi-at' },
    { label: 'Retroceder', value: 'pi pi-backward' },
    { label: 'Prohibido', value: 'pi pi-ban' },
    { label: 'Código de barras', value: 'pi pi-barcode' },
    { label: 'Barras de menú', value: 'pi pi-bars' },
    { label: 'Campana', value: 'pi pi-bell' },
    { label: 'Campana silenciada', value: 'pi pi-bell-slash' },
    { label: 'Bitcoin', value: 'pi pi-bitcoin' },
    { label: 'Rayo', value: 'pi pi-bolt' },
    { label: 'Libro', value: 'pi pi-book' },
    { label: 'Marcador', value: 'pi pi-bookmark' },
    { label: 'Marcador relleno', value: 'pi pi-bookmark-fill' },
    { label: 'Caja', value: 'pi pi-box' },
    { label: 'Maletín', value: 'pi pi-briefcase' },
    { label: 'Edificio', value: 'pi pi-building' },
    { label: 'Columnas de edificio', value: 'pi pi-building-columns' },
    { label: 'Diana', value: 'pi pi-bullseye' },
    { label: 'Calculadora', value: 'pi pi-calculator' },
    { label: 'Calendario', value: 'pi pi-calendar' },
    { label: 'Reloj de calendario', value: 'pi pi-calendar-clock' },
    { label: 'Quitar del calendario', value: 'pi pi-calendar-minus' },
    { label: 'Añadir al calendario', value: 'pi pi-calendar-plus' },
    { label: 'Cerrar calendario', value: 'pi pi-calendar-times' },
    { label: 'Cámara', value: 'pi pi-camera' },
    { label: 'Coche', value: 'pi pi-car' },
    { label: 'Triángulo abajo', value: 'pi pi-caret-down' },
    { label: 'Triángulo izquierda', value: 'pi pi-caret-left' },
    { label: 'Triángulo derecha', value: 'pi pi-caret-right' },
    { label: 'Triángulo arriba', value: 'pi pi-caret-up' },
    { label: 'Descargar carrito', value: 'pi pi-cart-arrow-down' },
    { label: 'Quitar del carrito', value: 'pi pi-cart-minus' },
    { label: 'Añadir al carrito', value: 'pi pi-cart-plus' },
    { label: 'Gráfico de barras', value: 'pi pi-chart-bar' },
    { label: 'Gráfico de líneas', value: 'pi pi-chart-line' },
    { label: 'Gráfico de tarta', value: 'pi pi-chart-pie' },
    { label: 'Gráfico de puntos', value: 'pi pi-chart-scatter' },
    { label: 'Check', value: 'pi pi-check' },
    { label: 'Check circular', value: 'pi pi-check-circle' },
    { label: 'Check cuadrado', value: 'pi pi-check-square' },
    { label: 'Chevron circular abajo', value: 'pi pi-chevron-circle-down' },
    { label: 'Chevron circular izquierda', value: 'pi pi-chevron-circle-left' },
    { label: 'Chevron circular derecha', value: 'pi pi-chevron-circle-right' },
    { label: 'Chevron circular arriba', value: 'pi pi-chevron-circle-up' },
    { label: 'Chevron abajo', value: 'pi pi-chevron-down' },
    { label: 'Chevron izquierda', value: 'pi pi-chevron-left' },
    { label: 'Chevron derecha', value: 'pi pi-chevron-right' },
    { label: 'Chevron arriba', value: 'pi pi-chevron-up' },
    { label: 'Círculo', value: 'pi pi-circle' },
    { label: 'Círculo relleno', value: 'pi pi-circle-fill' },
    { label: 'Círculo apagado', value: 'pi pi-circle-off' },
    { label: 'Círculo encendido', value: 'pi pi-circle-on' },
    { label: 'Portapapeles', value: 'pi pi-clipboard' },
    { label: 'Reloj', value: 'pi pi-clock' },
    { label: 'Clonar', value: 'pi pi-clone' },
    { label: 'Nube', value: 'pi pi-cloud' },
    { label: 'Descargar de la nube', value: 'pi pi-cloud-download' },
    { label: 'Subir a la nube', value: 'pi pi-cloud-upload' },
    { label: 'Código', value: 'pi pi-code' },
    { label: 'Engranaje', value: 'pi pi-cog' },
    { label: 'Comentario', value: 'pi pi-comment' },
    { label: 'Conversación', value: 'pi pi-comments' },
    { label: 'Brújula', value: 'pi pi-compass' },
    { label: 'Copiar', value: 'pi pi-copy' },
    { label: 'Tarjeta de crédito', value: 'pi pi-credit-card' },
    { label: 'Corona', value: 'pi pi-crown' },
    { label: 'Base de datos', value: 'pi pi-database' },
    { label: 'Borrar atrás', value: 'pi pi-delete-left' },
    { label: 'Escritorio', value: 'pi pi-desktop' },
    { label: 'Direcciones', value: 'pi pi-directions' },
    { label: 'Direcciones alternativo', value: 'pi pi-directions-alt' },
    { label: 'Discord', value: 'pi pi-discord' },
    { label: 'Dólar', value: 'pi pi-dollar' },
    { label: 'Descargar', value: 'pi pi-download' },
    { label: 'Expulsar', value: 'pi pi-eject' },
    { label: 'Puntos suspensivos H', value: 'pi pi-ellipsis-h' },
    { label: 'Puntos suspensivos V', value: 'pi pi-ellipsis-v' },
    { label: 'Sobre/Email', value: 'pi pi-envelope' },
    { label: 'Igual', value: 'pi pi-equals' },
    { label: 'Borrador', value: 'pi pi-eraser' },
    { label: 'Ethereum', value: 'pi pi-ethereum' },
    { label: 'Euro', value: 'pi pi-euro' },
    { label: 'Exclamación circular', value: 'pi pi-exclamation-circle' },
    { label: 'Triángulo de advertencia', value: 'pi pi-exclamation-triangle' },
    { label: 'Expandir', value: 'pi pi-expand' },
    { label: 'Enlace externo', value: 'pi pi-external-link' },
    { label: 'Ojo/Ver', value: 'pi pi-eye' },
    { label: 'Ojo tachado/Ocultar', value: 'pi pi-eye-slash' },
    { label: 'Cara sonriente', value: 'pi pi-face-smile' },
    { label: 'Facebook', value: 'pi pi-facebook' },
    { label: 'Retroceso rápido', value: 'pi pi-fast-backward' },
    { label: 'Avance rápido', value: 'pi pi-fast-forward' },
    { label: 'Archivo', value: 'pi pi-file' },
    { label: 'Subir archivo', value: 'pi pi-file-arrow-up' },
    { label: 'Archivo verificado', value: 'pi pi-file-check' },
    { label: 'Editar archivo', value: 'pi pi-file-edit' },
    { label: 'Archivo Excel', value: 'pi pi-file-excel' },
    { label: 'Exportar archivo', value: 'pi pi-file-export' },
    { label: 'Importar archivo', value: 'pi pi-file-import' },
    { label: 'Archivo esquema', value: 'pi pi-file-o' },
    { label: 'Archivo PDF', value: 'pi pi-file-pdf' },
    { label: 'Nuevo archivo', value: 'pi pi-file-plus' },
    { label: 'Archivo Word', value: 'pi pi-file-word' },
    { label: 'Filtro', value: 'pi pi-filter' },
    { label: 'Filtro relleno', value: 'pi pi-filter-fill' },
    { label: 'Quitar filtro', value: 'pi pi-filter-slash' },
    { label: 'Bandera', value: 'pi pi-flag' },
    { label: 'Bandera rellena', value: 'pi pi-flag-fill' },
    { label: 'Carpeta', value: 'pi pi-folder' },
    { label: 'Abrir carpeta', value: 'pi pi-folder-open' },
    { label: 'Añadir carpeta', value: 'pi pi-folder-plus' },
    { label: 'Avanzar', value: 'pi pi-forward' },
    { label: 'Medidor', value: 'pi pi-gauge' },
    { label: 'Regalo', value: 'pi pi-gift' },
    { label: 'Github', value: 'pi pi-github' },
    { label: 'Globo terráqueo', value: 'pi pi-globe' },
    { label: 'Google', value: 'pi pi-google' },
    { label: 'Birrete graduación', value: 'pi pi-graduation-cap' },
    { label: 'Martillo', value: 'pi pi-hammer' },
    { label: 'Hashtag', value: 'pi pi-hashtag' },
    { label: 'Auriculares', value: 'pi pi-headphones' },
    { label: 'Corazón', value: 'pi pi-heart' },
    { label: 'Corazón relleno', value: 'pi pi-heart-fill' },
    { label: 'Historial', value: 'pi pi-history' },
    { label: 'Inicio', value: 'pi pi-home' },
    { label: 'Reloj de arena', value: 'pi pi-hourglass' },
    { label: 'DNI / Tarjeta ID', value: 'pi pi-id-card' },
    { label: 'Imagen', value: 'pi pi-image' },
    { label: 'Imágenes', value: 'pi pi-images' },
    { label: 'Bandeja de entrada', value: 'pi pi-inbox' },
    { label: 'Rupia india', value: 'pi pi-indian-rupee' },
    { label: 'Información', value: 'pi pi-info' },
    { label: 'Información circular', value: 'pi pi-info-circle' },
    { label: 'Instagram', value: 'pi pi-instagram' },
    { label: 'Llave', value: 'pi pi-key' },
    { label: 'Idioma', value: 'pi pi-language' },
    { label: 'Bombilla', value: 'pi pi-lightbulb' },
    { label: 'Enlace', value: 'pi pi-link' },
    { label: 'Linkedin', value: 'pi pi-linkedin' },
    { label: 'Lista', value: 'pi pi-list' },
    { label: 'Lista de tareas', value: 'pi pi-list-check' },
    { label: 'Candado cerrado', value: 'pi pi-lock' },
    { label: 'Candado abierto', value: 'pi pi-lock-open' },
    { label: 'Mapa', value: 'pi pi-map' },
    { label: 'Marcador de mapa', value: 'pi pi-map-marker' },
    { label: 'Marte/Masculino', value: 'pi pi-mars' },
    { label: 'Megáfono', value: 'pi pi-megaphone' },
    { label: 'Microchip', value: 'pi pi-microchip' },
    { label: 'Microchip IA', value: 'pi pi-microchip-ai' },
    { label: 'Micrófono', value: 'pi pi-microphone' },
    { label: 'Microsoft', value: 'pi pi-microsoft' },
    { label: 'Menos', value: 'pi pi-minus' },
    { label: 'Menos circular', value: 'pi pi-minus-circle' },
    { label: 'Móvil', value: 'pi pi-mobile' },
    { label: 'Billetes', value: 'pi pi-money-bill' },
    { label: 'Luna', value: 'pi pi-moon' },
    { label: 'Columnas de objetos', value: 'pi pi-objects-column' },
    { label: 'Paleta', value: 'pi pi-palette' },
    { label: 'Clip', value: 'pi pi-paperclip' },
    { label: 'Pausa', value: 'pi pi-pause' },
    { label: 'Pausa circular', value: 'pi pi-pause-circle' },
    { label: 'Paypal', value: 'pi pi-paypal' },
    { label: 'Editar cuadrado', value: 'pi pi-pen-to-square' },
    { label: 'Lápiz', value: 'pi pi-pencil' },
    { label: 'Porcentaje', value: 'pi pi-percentage' },
    { label: 'Teléfono', value: 'pi pi-phone' },
    { label: 'Pinterest', value: 'pi pi-pinterest' },
    { label: 'Reproducir', value: 'pi pi-play' },
    { label: 'Reproducir circular', value: 'pi pi-play-circle' },
    { label: 'Más', value: 'pi pi-plus' },
    { label: 'Más circular', value: 'pi pi-plus-circle' },
    { label: 'Libra', value: 'pi pi-pound' },
    { label: 'Apagar', value: 'pi pi-power-off' },
    { label: 'Prime', value: 'pi pi-prime' },
    { label: 'Imprimir', value: 'pi pi-print' },
    { label: 'Código QR', value: 'pi pi-qrcode' },
    { label: 'Pregunta', value: 'pi pi-question' },
    { label: 'Pregunta circular', value: 'pi pi-question-circle' },
    { label: 'Recibo', value: 'pi pi-receipt' },
    { label: 'Reddit', value: 'pi pi-reddit' },
    { label: 'Refrescar', value: 'pi pi-refresh' },
    { label: 'Repetir', value: 'pi pi-replay' },
    { label: 'Responder', value: 'pi pi-reply' },
    { label: 'Guardar', value: 'pi pi-save' },
    { label: 'Buscar', value: 'pi pi-search' },
    { label: 'Reducir zoom', value: 'pi pi-search-minus' },
    { label: 'Aumentar zoom', value: 'pi pi-search-plus' },
    { label: 'Enviar', value: 'pi pi-send' },
    { label: 'Servidor', value: 'pi pi-server' },
    { label: 'Compartir', value: 'pi pi-share-alt' },
    { label: 'Escudo', value: 'pi pi-shield' },
    { label: 'Tienda', value: 'pi pi-shop' },
    { label: 'Bolsa de compra', value: 'pi pi-shopping-bag' },
    { label: 'Carrito de compra', value: 'pi pi-shopping-cart' },
    { label: 'Entrar', value: 'pi pi-sign-in' },
    { label: 'Salir', value: 'pi pi-sign-out' },
    { label: 'Mapa del sitio', value: 'pi pi-sitemap' },
    { label: 'Slack', value: 'pi pi-slack' },
    { label: 'Deslizadores H', value: 'pi pi-sliders-h' },
    { label: 'Deslizadores V', value: 'pi pi-sliders-v' },
    { label: 'Ordenar', value: 'pi pi-sort' },
    { label: 'Orden A-Z', value: 'pi pi-sort-alpha-down' },
    { label: 'Orden A-Z desc', value: 'pi pi-sort-alpha-down-alt' },
    { label: 'Orden Z-A', value: 'pi pi-sort-alpha-up' },
    { label: 'Orden Z-A desc', value: 'pi pi-sort-alpha-up-alt' },
    { label: 'Orden alt', value: 'pi pi-sort-alt' },
    { label: 'Quitar orden', value: 'pi pi-sort-alt-slash' },
    { label: 'Orden cantidad abajo', value: 'pi pi-sort-amount-down' },
    { label: 'Orden cantidad abajo alt', value: 'pi pi-sort-amount-down-alt' },
    { label: 'Orden cantidad arriba', value: 'pi pi-sort-amount-up' },
    { label: 'Orden cantidad arriba alt', value: 'pi pi-sort-amount-up-alt' },
    { label: 'Ordenar abajo', value: 'pi pi-sort-down' },
    { label: 'Ordenar abajo relleno', value: 'pi pi-sort-down-fill' },
    { label: 'Orden numérico abajo', value: 'pi pi-sort-numeric-down' },
    { label: 'Orden numérico abajo alt', value: 'pi pi-sort-numeric-down-alt' },
    { label: 'Orden numérico arriba', value: 'pi pi-sort-numeric-up' },
    { label: 'Orden numérico arriba alt', value: 'pi pi-sort-numeric-up-alt' },
    { label: 'Ordenar arriba', value: 'pi pi-sort-up' },
    { label: 'Ordenar arriba relleno', value: 'pi pi-sort-up-fill' },
    { label: 'Chispas', value: 'pi pi-sparkles' },
    { label: 'Cargando', value: 'pi pi-spinner' },
    { label: 'Cargando puntos', value: 'pi pi-spinner-dotted' },
    { label: 'Estrella', value: 'pi pi-star' },
    { label: 'Estrella rellena', value: 'pi pi-star-fill' },
    { label: 'Media estrella', value: 'pi pi-star-half' },
    { label: 'Media estrella rellena', value: 'pi pi-star-half-fill' },
    { label: 'Anterior', value: 'pi pi-step-backward' },
    { label: 'Anterior alternativo', value: 'pi pi-step-backward-alt' },
    { label: 'Siguiente', value: 'pi pi-step-forward' },
    { label: 'Siguiente alternativo', value: 'pi pi-step-forward-alt' },
    { label: 'Parar', value: 'pi pi-stop' },
    { label: 'Parar circular', value: 'pi pi-stop-circle' },
    { label: 'Cronómetro', value: 'pi pi-stopwatch' },
    { label: 'Sol', value: 'pi pi-sun' },
    { label: 'Sincronizar', value: 'pi pi-sync' },
    { label: 'Tabla', value: 'pi pi-table' },
    { label: 'Tablet', value: 'pi pi-tablet' },
    { label: 'Etiqueta', value: 'pi pi-tag' },
    { label: 'Etiquetas', value: 'pi pi-tags' },
    { label: 'Telegram', value: 'pi pi-telegram' },
    { label: 'Mosaico grande', value: 'pi pi-th-large' },
    { label: 'No me gusta', value: 'pi pi-thumbs-down' },
    { label: 'No me gusta relleno', value: 'pi pi-thumbs-down-fill' },
    { label: 'Me gusta', value: 'pi pi-thumbs-up' },
    { label: 'Me gusta relleno', value: 'pi pi-thumbs-up-fill' },
    { label: 'Chincheta', value: 'pi pi-thumbtack' },
    { label: 'Ticket', value: 'pi pi-ticket' },
    { label: 'Tiktok', value: 'pi pi-tiktok' },
    { label: 'Cerrar', value: 'pi pi-times' },
    { label: 'Cerrar circular', value: 'pi pi-times-circle' },
    { label: 'Papelera', value: 'pi pi-trash' },
    { label: 'Trofeo', value: 'pi pi-trophy' },
    { label: 'Camión', value: 'pi pi-truck' },
    { label: 'Lira turca', value: 'pi pi-turkish-lira' },
    { label: 'Twitch', value: 'pi pi-twitch' },
    { label: 'Twitter', value: 'pi pi-twitter' },
    { label: 'Deshacer', value: 'pi pi-undo' },
    { label: 'Desbloquear', value: 'pi pi-unlock' },
    { label: 'Subir', value: 'pi pi-upload' },
    { label: 'Usuario', value: 'pi pi-user' },
    { label: 'Editar usuario', value: 'pi pi-user-edit' },
    { label: 'Quitar usuario', value: 'pi pi-user-minus' },
    { label: 'Añadir usuario', value: 'pi pi-user-plus' },
    { label: 'Usuarios', value: 'pi pi-users' },
    { label: 'Venus/Femenino', value: 'pi pi-venus' },
    { label: 'Verificado', value: 'pi pi-verified' },
    { label: 'Vídeo', value: 'pi pi-video' },
    { label: 'Vimeo', value: 'pi pi-vimeo' },
    { label: 'Bajar volumen', value: 'pi pi-volume-down' },
    { label: 'Silenciar volumen', value: 'pi pi-volume-off' },
    { label: 'Subir volumen', value: 'pi pi-volume-up' },
    { label: 'Cartera', value: 'pi pi-wallet' },
    { label: 'Almacén', value: 'pi pi-warehouse' },
    { label: 'Pulso', value: 'pi pi-wave-pulse' },
    { label: 'Whatsapp', value: 'pi pi-whatsapp' },
    { label: 'Wifi', value: 'pi pi-wifi' },
    { label: 'Maximizar ventana', value: 'pi pi-window-maximize' },
    { label: 'Minimizar ventana', value: 'pi pi-window-minimize' },
    { label: 'Llave inglesa', value: 'pi pi-wrench' },
    { label: 'Youtube', value: 'pi pi-youtube' }
  ];


  // Update tab name
  setPageTitle(pageName: string) {
    if(this.authService.isManager() || this.authService.isAdmin()){
      this.titleService.setTitle(`${pageName} - ${this.ADMIN_APP_NAME}`);
    }
    else this.titleService.setTitle(`${pageName} - ${this.CLIENT_APP_NAME}`);
  }

  setTitle(fullTitle: string) {
    this.titleService.setTitle(fullTitle);
  }

  addToTitle(textToAppend: string, separator: string = ' - ') {
    const currentTitle = this.titleService.getTitle();
    if (!currentTitle.includes(textToAppend)) {
      this.titleService.setTitle(`${currentTitle}${separator}${textToAppend}`);
    }
  }

  prependToTitle(textToPrepend: string, separator: string = ' - ') {
    const currentTitle = this.titleService.getTitle();
    this.titleService.setTitle(`${textToPrepend}${separator}${currentTitle}`);
  }

  //Works either with 'client'-like literals or with a route '/photo.png'
  setFavicon(keyOrUrl: string) {
    const finalUrl = this.PREDEFINED_ICONS[keyOrUrl] || keyOrUrl;
    this.updateFaviconTag(finalUrl);
  }

  private updateFaviconTag(url: string) {
    const link: HTMLLinkElement = document.querySelector("link[rel~='icon']") || document.createElement('link');
    link.rel = 'icon';
    link.href = url;
    if (!document.head.contains(link)) {
      document.head.appendChild(link);
    }
  }

  //Reset
  resetDefault() {
    this.setTitle(this.CLIENT_APP_NAME);
    if(this.authService.isAdmin()){
      this.setFavicon(this.APP_ADMIN_LOGO);
    }
    else{
      this.setFavicon(this.APP_USER_LOGO);
    }
  }
}
