spring.application.name=ProjectBackend

server.port = 443

management.endpoints.web.exposure.include=health,info,metrics
spring.jpa.open-in-view=true

spring.config.import=optional:file:.env

#As it is a dummy SSL certificate to enable SSL (HTTPS), it does not need an env variable, as the real certificate will never be uploaded
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=password
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=selfsigned

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}

spring.data.mongodb.uri=${MONGODB_URI}
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# Application log levels: manually-generated, Spring Security, Spring Web, requests details
# Levels (more to less info): TRACE, DEBUG, INFO, WARN, ERROR
logging.level.com.tfg.backend=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
spring.mvc.log-request-details=true

# Enable classic path matcher (useful for SPAController)
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# DB log levels: Queries, field-value assignments per query, DB mode, SQL formatting
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=INFO
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true

# Custom logs settings: Do not include traces in responses, enable Spring ProblemDetails library for enhanced error responses
server.error.include-stacktrace=never
spring.mvc.problem-details.enabled=true

# JWT and payment cards DB keys
jwt.secret=${JWT_SECRET}
app.cards-db.key=${CARDS_DB_KEY}

# Options: all, none, users, categories, products, shops, orders, stock, reviews
app.db.init=all

# Swagger and API Docs enablements
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# MinIO parameters (Change with real S3 properties when required)
# minio.url contains the URL in which images are treated within the app
# minio.public-url contains the URL in which images are served in browsers
minio.url=${S3_ENDPOINT}
minio.public-url=${S3_PUBLIC_URL}
minio.access-key=${S3_ACCESS_KEY}
minio.secret-key=${S3_SECRET_KEY}
minio.bucket-name=${S3_BUCKET_NAME}
minio.ssl.insecure=true

# Locally stored environment variables, such as SENDER_MAIL_PORT, have to be imported in GitHub runners in the env section of the corresponding step
# Environment variables values like this will be securely stored using GitHub Secrets and accesible via reference (${{ secrets.SENDER_MAIL_PORT }})
spring.mail.host=smtp.gmail.com
spring.mail.port=${SENDER_MAIL_PORT}
spring.mail.username=${SENDER_MAIL_ADDRESS}
spring.mail.password=${SENDER_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
google.auth.clientId=${GOOGLE_AUTH_CLIENT_ID}