# In test mode, Spring firstly reads application.properties, and then only overrides these variables with the values in this file

# Independent DB connection
spring.datasource.url=jdbc:mysql://localhost:3306/FrictTest?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=p4ssw0rd

# Create objects and clean DB at the end
spring.jpa.hibernate.ddl-auto=create-drop

# Do not initialize any data when running DatabaseInitializer class
app.db.init=none

# MinIO empty test container (tests execution only)
minio.url=https://localhost:9000
minio.public-url=https://localhost:9000
minio.access-key=admin
minio.secret-key=password123
minio.bucket-name=images
minio.ssl.insecure=true