name: Code analysis with Sonarqube

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  RUNNER_DB_NAME: FrictTest
  RUNNER_DB_PASSWORD: p4ssw0rd
  RUNNER_MINIO_USER: admin
  RUNNER_MINIO_PASSWORD: password123
  RUNNER_MINIO_BUCKET_NAME: images

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: ${{ env.RUNNER_DB_NAME }}
          MYSQL_ROOT_PASSWORD: ${{ env.RUNNER_DB_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Start MongoDB Replica Set
        run: |
          docker run -d -p 27017:27017 --name mongodb \
            -e MONGO_INITDB_ROOT_USERNAME=admin \
            -e MONGO_INITDB_ROOT_PASSWORD=password123 \
            mongo:latest \
            sh -c "echo 'frictSuperSecretReplicaKey123456' > /data/keyfile && chmod 400 /data/keyfile && chown 999:999 /data/keyfile && exec /usr/local/bin/docker-entrypoint.sh mongod --replSet rs0 --keyFile /data/keyfile --bind_ip_all"
          
          sleep 10
          docker exec mongodb mongosh --username admin --password password123 --authenticationDatabase admin --eval "rs.initiate({_id:'rs0',members:[{_id:0,host:'127.0.0.1:27017'}]})"

      - name: Start MinIO and Create Bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ env.RUNNER_MINIO_USER }}
          AWS_SECRET_ACCESS_KEY: ${{ env.RUNNER_MINIO_PASSWORD }}
          AWS_REGION: us-east-1
        run: |
          mkdir -p /tmp/minio_certs
          cp -r $(pwd)/docker/minio_https/certs/* /tmp/minio_certs/

          docker run -d \
            -p 9000:9000 \
            -p 9001:9001 \
            --name minio \
            -v /tmp/minio_certs:/root/.minio/certs \
            -e MINIO_ROOT_USER=${{ env.RUNNER_MINIO_USER }} \
            -e MINIO_ROOT_PASSWORD=${{ env.RUNNER_MINIO_PASSWORD }} \
            minio/minio server /data --console-address ":9001"

          sleep 5

          aws --endpoint-url https://localhost:9000 --no-verify-ssl s3 mb s3://${{ env.RUNNER_MINIO_BUCKET_NAME }}


      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'


      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json


      - name: Install Frontend Dependencies
        working-directory: frontend
        run: |
          npm ci
          npm install -g @angular/cli


      - name: Start Angular project
        working-directory: frontend
        run: ng serve --proxy-config proxy-test.conf.json &


      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar


      - name: Build and analyze
        working-directory: backend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=codeurjc-students_2025-Frict -Dspring.profiles.active=test